add `TServerEventHandler` to clean threadlocal  token in `TokenWrappingHMSHandler`
ExpediaGroup/waggle-dance pull request #276
Opened 2023-05-27 07:45 UTC by zzzzming95

### :pencil: Description

In this issue https://github.com/ExpediaGroup/waggle-dance/pull/266 , we support kerberos and delegation tokne via TokenWrappingHMSHandler. We found that some time threadload of `TokenWrappingHMSHandler` not be clean when the concurrency is high. So using `TServerEventHandler` to trigger threadlocal remove.

Reference:https://github.com/apache/hive/blob/7bfc54ffc8baf5f3e7de326b750fe9355b11132b/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java#L651

test：Manual testing

### :link: Related Issues
no

2023-05-27 10:01 UTC, jmnunezizu commented
Hi @zzzzming95 – thanks for submitting another PR.
Please send me a private message via LinkedIn. I'd like to get more details about your Waggle Dance usage and future use cases. Thanks.

2023-05-29 13:42 UTC, patduin approved these changes

2023-05-29 13:45 UTC, patduin requested changes
Could you add a line in the change log please?

Header can be, once merge we'll fill in the release date + a line with the fix + link to issue.
```
[3.11.1] - TBD
```

2023-05-30 14:16 UTC, abhimanyugupta07 approved these changes

2023-05-31 08:34 UTC, merged