Test PR Added the metrics with tags for filtering in datadog
ExpediaGroup/waggle-dance pull request #282
Opened 2023-08-15 10:57 UTC by DhrubajyotiSadhu

### :pencil: Description

### :link: Related Issues

2023-08-15 17:14 UTC, RickArt requested changes

2023-08-16 10:10 UTC, DhrubajyotiSadhu commented on pom.xml
> +  <version>3.11.4-SNAPSHOT</version>
Yanked it as there is already a release

2023-08-16 10:10 UTC, DhrubajyotiSadhu commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/metrics/MonitoredAspect.java
> +    String newMetricBasePath = buildMetricWithTagsBasePath(pjp);
Done. Thanks for the suggestion.

2023-08-16 10:16 UTC, DhrubajyotiSadhu commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/metrics/MonitoredAspect.java
> +    return new StringBuilder(methodName).toString();
resolved it.

2023-08-16 11:37 UTC, abhimanyugupta07 commented on CHANGELOG.md
> +- Exclude jetty-all from core module, because it makes spring start fail and makes `WaggleDanceIntegrationTest` fail.
don't think we need to add the previous changelog here.

cc @patduin what you think

2023-08-16 11:38 UTC, abhimanyugupta07 commented on pom.xml
> +  <version>3.11.4-SNAPSHOT</version>
The release was made in error.

2023-08-16 11:50 UTC, abhimanyugupta07 commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/metrics/MonitoredAspect.java
> +  private String buildMetricWithTagsBasePath(ProceedingJoinPoint pjp) {
I don't see this function used actually.

2023-08-16 11:53 UTC, abhimanyugupta07 commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/metrics/MonitoredAspect.java
>        increment(buildMetricPath(COUNTER, metricBasePath, getMonitorMetastore(), result));
If we are always going to send both metrics (with and without tags), I don't see much reason for having two kind of methods, increment, incrementWithTags, submit, submitWithTags. 

We can just add the functionality to increment and submit methods. You can add the comment "Sends metrics with Tags: federation_namespace and method_name" in there.

2023-08-16 13:48 UTC, patduin commented on waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/metrics/MonitoredAspectTest.java
> +    assertThat(((CumulativeCounter) ((ArrayList) meters).get(0)).count(), is(1.0));
this double cast is very hard to read, why don't you follow the examples from the other tests?
```
 RequiredSearch rs = meterRegistry.get("counter.Type_Anonymous.success");
 assertThat(rs.counter().count(), is(1.0));
 ```

2023-08-16 13:49 UTC, patduin commented on waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/metrics/MonitoredAspectTest.java
> +  public void monitorSuccessWithTags() throws Throwable {
We're not testing the tags, please add asserts that the correct tags are stored.

2023-08-16 13:50 UTC, patduin commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/metrics/MonitoredAspect.java
> +    return new StringBuilder(className).toString();
correct, just `return className`

2023-08-16 13:57 UTC, patduin commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/metrics/MonitoredAspect.java
> +    return new StringBuilder(className).toString();
but better to delete the whole method as it is unused

2023-08-16 14:01 UTC, patduin commented on waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/metrics/MonitoredAspectTest.java
>      assertThat(rs.timer().count(), is(1L));
Please also add asserts to this integration test: https://github.com/ExpediaGroup/waggle-dance/blob/main/waggle-dance-integration-tests/src/test/java/com/hotels/bdp/waggledance/WaggleDanceIntegrationTest.java#L403

2023-08-16 15:51 UTC, massdosage commented
I have a question at a higher level - how many tags will this add to each metric? Bear in mind that Datadog calculates the cost of custom metrics (more or less) as: "metric name X host X tag" so each tag you add is going to increase your custom metric costs. I'm just checking whether this will cause a cost issue or the cardinality of the tag values will be low enough that this won't be an issue.

2023-08-18 14:45 UTC, patduin commented on CHANGELOG.md
> +## [3.11.4] - 2023-08-16
update the date please

2023-08-18 14:50 UTC, patduin approved these changes

2023-08-23 17:18 UTC, RickArt approved these changes

2023-08-23 17:32 UTC, merged