Add personalized configuration parameters for each metastore.
ExpediaGroup/waggle-dance pull request #315
Opened 2024-04-14 12:44 UTC by yangyuxia

### :pencil: Description
Different hive Metastores may have different parameter values for the same parameter. If multiple federated Metastores are configured in waggle dance, you can configure their own parameter values for each metastore.
For example, when hivemetastore enabled the kerberos authentication, the value of the "hive.metastore.kerberos.principal", some metastore is configured to "hive/_HOST@Realm", but some metastore is configured as "hive/{clusterName}@Realm", so you need to configure personalized configuration parameters for each metastore. 

### :link: Related Issues

2024-04-15 02:00 UTC, yangyuxia commented
cat waggle-dance-server.yml

verbose: true
port: 48869
database-resolution: PREFIXED
yaml-storage:
 &nbsp;overwrite-config-on-shutdown: false
logging:
 &nbsp;config: file:${WAGGLE_DANCE_HOME}/conf/log4j2.xml
configuration-properties:
 &nbsp;hadoop.security.authentication: KERBEROS
 &nbsp;hadoop.kerberos.keytab.login.autorenewal.enabled: true
 &nbsp;hadoop.proxyuser.hive.users: '*'
 &nbsp;hadoop.proxyuser.hive.groups: '*'
 &nbsp;hadoop.proxyuser.hive.hosts: '*'
 &nbsp;hive.metastore.sasl.enabled: true
 &nbsp;hive.metastore.kerberos.principal: hive/_HOST@HADOOP.COM
 &nbsp;hive.metastore.kerberos.keytab.file: ${WAGGLE_DANCE_HOME}/conf/wd.keytab
 &nbsp;hive.cluster.delegation.token.store.class: org.apache.hadoop.hive.thrift.ZooKeeperTokenStore
 &nbsp;hive.cluster.delegation.token.store.zookeeper.connectString: host-zk1:2181,host-zk2:2181,host-zk3:2181
 &nbsp;hive.cluster.delegation.token.store.zookeeper.znode: /hive/cluster/delegationwg
 &nbsp;hive.cluster.delegation.token.store.zookeeper.acl: "world:anyone:rwcda"
 &nbsp;hive.server2.authentication: KERBEROS
 &nbsp;hive.server2.authentication.kerberos.keytab: ${WAGGLE_DANCE_HOME}/conf/wd.keytab
 &nbsp;hive.server2.authentication.kerberos.principal: hive/_HOST@HADOOP.COM
 &nbsp;hive.server2.authentication.client.kerberos.principal: hive/_HOST@HADOOP.COM
 &nbsp;wd-metastore:
 &nbsp;&nbsp;hms1:
 &nbsp;&nbsp;&nbsp;&nbsp;hive.metastore.kerberos.principal: hive/_HOST@HADOOP.COM
 &nbsp;&nbsp;hms2:
 &nbsp;&nbsp;&nbsp;&nbsp;hive.metastore.kerberos.principal: hive/test2@HADOOP.COM

2024-04-16 11:49 UTC, patduin commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/client/CloseableThriftHiveMetastoreIfaceClientFactory.java
> +      Map<String, String> serverConfigMap=waggleDanceConfiguration.getConfigurationProperties();
I suggest we move these properties to the AbstractMetastore class and make it part of the waggle-dance-federation.yml and this code can become much simpler like:

```
properties.putAll(waggleDanceConfiguration.getConfigurationProperties());
//override per metastore
properties.putAll(metastore.getConfigurationProperties());
```

2024-04-16 11:49 UTC, patduin requested changes
Thank you please have a look and my comment.

2024-04-22 06:29 UTC, yangyuxia commented
primary-meta-store:
  database-prefix: ''
  name: hms1
  remote-meta-store-uris: thrift://host-hms1:9083
  access-control-type: READ_AND_WRITE_AND_CREATE
  impersonation-enabled: false
  configuration-properties:
    hive.metastore.kerberos.principal: hive/hms@HADOOP.COM
    hive.server2.enable.doAs: true

2024-05-06 07:41 UTC, patduin commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/client/CloseableThriftHiveMetastoreIfaceClientFactory.java
> +    properties.putAll(metaStore.getConfigurationProperties());
Could you add a junit test please?

2024-05-11 09:41 UTC, yangyuxia commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/client/CloseableThriftHiveMetastoreIfaceClientFactory.java
> +    properties.putAll(metaStore.getConfigurationProperties());
added

2024-05-21 14:58 UTC, patduin commented on waggle-dance-api/src/main/java/com/hotels/bdp/waggledance/api/model/AbstractMetaStore.java
> +  private transient Map<String, String> databaseNameMapping = Collections.emptyMap();
why this had to change?

2024-05-22 17:34 UTC, jmnunezizu requested changes

2024-05-22 17:34 UTC, jmnunezizu commented on waggle-dance-api/src/main/java/com/hotels/bdp/waggledance/api/model/AbstractMetaStore.java
> +  public Map<String, String> getConfigurationProperties() {
Please move these two methods below the `setDatabaseNameMapping` method to keep them in sync with the property definitions. Normally, `toString` (if defined) is the last method in a class.

2024-05-22 17:34 UTC, jmnunezizu commented on waggle-dance-core/src/main/java/com/hotels/bdp/waggledance/client/CloseableThriftHiveMetastoreIfaceClientFactory.java
> +    //override per metastore
The comment isn't needed. 
nit: there's a space missing between `if` and `(`. You might also want to leave an empty line before the `return` statement to improve readability.

2024-05-22 17:34 UTC, jmnunezizu commented on waggle-dance-core/src/test/java/com/hotels/bdp/waggledance/client/CloseableThriftHiveMetastoreIfaceClientFactoryTest.java
> +    fed1.setConfigurationProperties(Collections.singletonMap(ConfVars.METASTORE_KERBEROS_PRINCIPAL.varname,"hive/_HOST@HADOOP.COM"));
Nit: there's a space missing between the key and the value.

2024-05-22 17:37 UTC, jmnunezizu commented
Thanks for the contribution. Please update the readme explaining how this works and how it can be utilised. Thanks.

2024-05-24 09:54 UTC, jmnunezizu approved these changes
Thanks!

2024-05-24 14:59 UTC, patduin commented on waggle-dance-api/src/main/java/com/hotels/bdp/waggledance/api/model/AbstractMetaStore.java
> +  private Map<String, String> configurationProperties;// = Collections.emptyMap();
@yangyuxia if you could revert or explain why this change was made I'm happy to approver once that's done,thanks!

2024-05-24 14:59 UTC, patduin commented on waggle-dance-api/src/main/java/com/hotels/bdp/waggledance/api/model/AbstractMetaStore.java
> +  private transient Map<String, String> databaseNameMapping = Collections.emptyMap();
@yangyuxia if you could revert or explain why this change was made I'm happy to approver once that's done,thanks!

2024-05-26 11:23 UTC, patduin approved these changes
Thank you

2024-05-27 09:39 UTC, merged